# Generated by Django 5.0.1 on 2024-03-26 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0007_apropos_update_at_article_update_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='vitrine/static/services/'),
        ),
    ]
