# Generated by Django 4.1.13 on 2024-04-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0010_agence_autre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='Equipe/')),
            ],
        ),
        migrations.AddField(
            model_name='agence',
            name='adresse',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='agence',
            name='rue',
            field=models.CharField(max_length=300),
        ),
    ]
