# Generated by Django 4.1.13 on 2024-04-15 12:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0011_equipe_agence_adresse_alter_agence_rue'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='equipe',
            name='update_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
