# Generated by Django 4.1.13 on 2024-04-17 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0012_equipe_date_equipe_update_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agence',
            name='rue',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
