# Generated by Django 4.1.13 on 2024-04-17 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0013_alter_agence_rue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agence',
            name='rue',
        ),
    ]
