# Generated by Django 4.1.13 on 2024-04-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0014_remove_agence_rue'),
    ]

    operations = [
        migrations.AddField(
            model_name='autre',
            name='pourquoi',
            field=models.TextField(blank=True),
        ),
    ]
