# Generated by Django 4.1.13 on 2024-04-29 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0015_autre_pourquoi'),
    ]

    operations = [
        migrations.AddField(
            model_name='agence',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='autre',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='equipe',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
