# Generated by Django 4.1.13 on 2024-04-30 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0016_agence_is_active_autre_is_active_equipe_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='promotion',
            field=models.BooleanField(default=False),
        ),
    ]
